feat: add footer
divyanshugarg36/brlcad-docs pull request #2
Opened 2022-08-24 18:52 UTC by divyanshugarg36

- add social icon svg

2022-09-05 05:38 UTC, theamanjs requested changes

2022-09-05 05:38 UTC, theamanjs commented on ui-supplemental/partials/footer-content.hbs
> +</footer>
Please add a new empty line in the eof

2022-09-06 17:06 UTC, divyanshugarg36 commented on ui-supplemental/partials/footer-content.hbs
> +</footer>
Fixed

2022-09-07 05:56 UTC, theamanjs approved these changes

2022-09-07 06:35 UTC, merged